server:
    bind:
        host: ${WOUDC_API_BIND_HOST}
        port: ${WOUDC_API_BIND_PORT}
    url: ${WOUDC_API_URL}
    basepath: /
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    languages:
        - en-CA
        - fr-CA
    # cors: true
    pretty_print: true
    limit: 500
    # templates: /path/to/templates
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    ogc_schemas_location: ${WOUDC_API_OGC_SCHEMAS_LOCATION}

logging:
    level: ERROR
    # logfile: /tmp/woudc-api.log

metadata:
    identification:
        title: World Ozone and Ultraviolet Radiation Data Centre (WOUDC)
        description: The World Ozone and Ultraviolet Radiation Data Centre (WOUDC) is one of six World Data Centres which are part of the Global Atmosphere Watch (GAW) programme of the World Meteorological Organization (WMO).  WOUDC contains ozone and UV data measured by instruments located on ground-based, shipborne or airborne platforms.  Data are subject to the WOUDC Data Policy (https://woudc.org/about/data-policy.php)
        keywords:
            - ozone
            - ultraviolet
            - uv
            - totalozone
            - ozonesonde
            - umkehr
            - gaw
            - wmo
            - spectral
            - stations
            - instruments
        keywords_type: theme
        terms_of_service: https://www.canada.ca/en/environment-climate-change/corporate/transparency.html
        url: https://woudc.org
    license:
        name: WOUDC Data Use Policy
        url: https://woudc.org/about/data-policy.php
    provider:
        name: Government of Canada, Environment and Climate Change Canada, Meteorological Service of Canada
        url: https://www.canada.ca/en/services/environment/weather.html
    contact:
        name: World Ozone and Ultraviolet Radiation Data Centre
        position: Data Centre Manager
        phone: None
        fax: None
        address: 4905 Dufferin Street
        city: Toronto
        stateorprovince: Ontario
        postalcode: M3H 5T4
        country: Canada
        email: woudc@ec.gc.ca
        url: https://woudc.org/contact.php
        hours: 1400h - 2200h UTC
        instructions: During hours of service

resources:
    projects:
        type: collection
        title: WOUDC Data Registry Projects
        description: Connection to projects in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.project
              id_field: identifier
    discovery_metadata:
        type: collection
        title: WOUDC Data Registry Discovery Metadata
        description: Connection to dataset metadata in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.discovery_metadata
              id_field: identifier
    datasets:
        type: collection
        title: WOUDC Data Registry Datasets
        description: Connection to datasets in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.dataset
              id_field: identifier
    countries:
        type: collection
        title: WOUDC Data Registry Countries
        description: Connection to countries in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.country
              id_field: identifier
    contributors:
        type: collection
        title: WOUDC Data Registry Contributors
        description: Connection to contributors in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.contributor
              id_field: identifier
    stations:
        type: collection
        title: WOUDC Data Registry Stations
        description: Connection to stations in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.station
              id_field: woudc_id
    instruments:
        type: collection
        title: WOUDC Data Registry Instruments
        description: Connection to instruments in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.instrument
              id_field: identifier
    deployments:
        type: collection
        title: WOUDC Data Registry Deployments
        description: Connection to contributor deployments in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.deployment
              id_field: identifier
    data_records:
        type: collection
        title: WOUDC Data Registry Data Records
        description: Connection to data records in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18T00:00:00Z
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.data_record
              id_field: identifier
              time_field: timestamp_utc
    notifications:
        type: collection
        title: WOUDC notifications
        description: WOUDC notifications
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2015-02-03
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.notification
              id_field: published_date
              date_field: published_date
    peer_data_records:
        type: collection
        title: WOUDC Peer Data Records
        description: Connection to data from federated data centres in the WOUDC Data Registry Search Index
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18T00:00:00Z
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.peer_data_record
              id_field: identifier
              time_field: start_datetime
    uv_index_hourly:
        type: collection
        title: WOUDC UV Index Hourly
        description: Connection to uv_index_hourly in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox:  [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18T00:00:00Z
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.uv_index_hourly
              id_field: identifier
              time_field: timestamp_utc
    totalozone:
        type: collection
        title: WOUDC Total Ozone
        description: Connection to totalozone in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18T00:00:00Z
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.totalozone
              id_field: identifier
              time_field: observation_date
    ozonesonde:
        type: collection
        title: WOUDC OzoneSonde
        description: Connection to ozonesonde in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18T00:00:00Z
                end: null # or empty
        providers:
            - type: feature
              name: woudc_api.provider.elasticsearch.ElasticsearchWOUDCProvider
              data: ${WOUDC_API_ES_URL}/${WOUDC_API_ES_INDEX_PREFIX}.ozonesonde
              id_field: identifier
              time_field: timestamp_date

    woudc-data-registry-metrics:
        type: process
        processor:
            name: woudc_api.plugins.metrics.MetricsProcessor
    woudc-data-registry-explore:
        type: process
        processor:
            name: woudc_api.plugins.explore.SearchPageProcessor
    woudc-data-registry-select-distinct:
        type: process
        processor:
            name: woudc_api.plugins.distinct.GroupSearchProcessor
    woudc-data-registry-validate:
        type: process
        processor:
            name: woudc_api.plugins.validate.ExtendedCSVProcessor
